name: Build
on:
  push:
    branches:
      - origin
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          run: |  
            docker run \
                --rm \
                -e SONAR_HOST_URL="http://${SONARQUBE_URL}"  \
                -e SONAR_TOKEN="myAuthenticationToken" \
                -v "${YOUR_REPO}:/usr/src" \
                sonarsource/sonar-scanner-cli:4.7.0

      - name: Run SonarScanner with Java 17
        run: |
          export JAVA_HOME=${{ steps.setup-java.outputs.java-home }}
          export PATH=$JAVA_HOME/bin:$PATH
          sonar-scanner -X

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar.projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar.organization: ${{ secrets.SONAR_ORG }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

