name: Build
on:
  push:
    branches:
      - origin
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install Latest SonarScanner
        run: |
          # Get the latest version number from GitHub releases
          LATEST_VERSION=$(curl -s https://api.github.com/repos/SonarSource/sonar-scanner-cli/releases/latest | jq -r .tag_name)
          
          # Download and install the latest version of SonarScanner
          wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/${LATEST_VERSION}/sonar-scanner-${LATEST_VERSION}-linux.zip
          unzip sonar-scanner-${LATEST_VERSION}-linux.zip -d /opt/
          
          # Add SonarScanner to PATH
          export PATH=$PATH:/opt/sonar-scanner-${LATEST_VERSION}-linux/bin

      - name: Install jq
        run: sudo apt-get install jq

      - name: Run SonarScanner with Java 17
        run: |
          export JAVA_HOME=${{ steps.setup-java.outputs.java-home }}
          export PATH=$JAVA_HOME/bin:$PATH
          sonar-scanner -X

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar.projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar.organization: ${{ secrets.SONAR_ORG }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

